version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: my-redis-instance
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
  mysql:
    image: mysql:8.0 # Use the desired MySQL image version
    environment:
      MYSQL_ROOT_PASSWORD: xsnail # Set a strong root password
      MYSQL_DATABASE: rediskme # Optional: Create a default database
      MYSQL_USER: caramujox # Optional: Create a default user
      MYSQL_PASSWORD: caramujox # Optional: Set password for the default user
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
volumes:
  redis_data:
  db_data: # Optional: Define a volume for MySQL data persistence